### ISSUE TITLE
ConnectToMeshcatVisualizer Broken Due to Drake Deprecation

### ISSUE THREAD

**Issue by kwesiRutledge** [vincekurtz/kinova_drake#7]
It appears that the `ConnectMeshcatVisualizer()` method is being deprecated soon. (On some of our Docker containers using the official Drake image, it looks like it already has been made unavailable and we cannot use some parts of `kinova_drake`!)

We found that the following fix worked in some of our smaller, internal examples, if I have the time I will update my branch and open a pull request to send the fix to you:
```
# Connect to Meshcat
# meshcat = ConnectMeshcatVisualizer(builder=builder,
#                                                                   zmq_url = zmq_url,
#                                                                   scene_graph = scene_graph,
#                                                                   output_port = scene_graph.get_query_output_port())

meshcat0 = Meshcat(port=7001) # Object provides an interface to Meshcat
mCpp = MeshcatVisualizerCpp(meshcat0)
mCpp.AddToBuilder(builder,scene_graph,meshcat0)
```

**Comment by vincekurtz** [comment]
Hi Kwesi - it was great to see you in person at ACC the other week! I just pushed some changes that should address the issue. Please let me know if I missed anything. Thanks!

**Comment by kwesiRutledge** [comment]
Excellent! Your fix works like a charm! Thanks a bunch for your help on this!

(It was also great to see you in person last week! And good luck this summer on the internship!!)
