### ISSUE TITLE
Point cloud example

### ISSUE THREAD

**Issue by hermattt** [vincekurtz/kinova_drake#8]
Hi,

I successfully ran all the simulation examples except the point cloud (or whenever camera is included simulation_demo include_camera = True). 
Error:
```
Traceback (most recent call last):
  File "/home/kinova/Desktop/kinova_drake/examples/point_cloud_demo.py", line 32, in <module>
    station.AddCamera()
  File "/home/kinova/Desktop/kinova_drake/kinova_station/simulation_station.py", line 374, in AddCamera
    self.scene_graph.AddRenderer(renderer_name,
RuntimeError: OBJ has no normals: /home/kinova/Desktop/kinova_drake/models/gen3_7dof/meshes/forearm_link.obj
```
Is it Drake deprecation or I`m missing something? I can't find that forearm kinova model with normals.
Any ideas how to resolve this issue?

**Comment by vincekurtz** [comment]
I'm guessing it's a Drake deprecation thing, they might have gotten stricter about mesh parsing recently. I'll look into it.

**Comment by vincekurtz** [comment]
Ok, just fixed I think. Looks like the camera rendering pipeline changed recently, including stricter checks for mesh properties. I added normals to the meshes (for future reference, `meshlabserver -i foo.obj -o foo.obj -m vn` does the trick) along with a few other small deprecation fixes. 

Everything should work with the latest Drake (v1.19.0) now. Let me know if that's not the case, or if you find any other problematic meshes. Thanks for bringing this to my attention!
